#sdk: "/Users/massey/.rvm/gems/ruby-1.9.3-p392/gems/rhodes-4.0.0.beta.28"
sdkversion: "4.0.0"
name: "chi311_all"
version: 1.0
vendor: "rhomobile"
build: "debug"
bbver: 6.0
applog: "rholog.txt"
iphone:
  configuration: "Release"
  sdk: "iphonesimulator6.0"
  provisionprofile: 
  codesignidentity: 
  entitlements: 
  BundleIdentifier: "com.rhomobile.chi311all"
  BundleURLScheme: "chi311all"
wp:
  productid: "ce70b3f0-cc09-0130-b498-282066131a87"
symbian:
  uid: "0xe4640e70"
android:
  version: 2.1
extensions:
  - json
  - rexml
  - set
  - rhoconnect-client

